apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
      - name: cal-app
        image: elmaqoo2024/cal-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://myUser:myPassword@mongodb-service:27017/mydatabase"
