version: '3.8'

services:
  webapp:
    image: elmaqoo2024/cal-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myUser
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
